### ISSUE TITLE
svg icons doesn't work

### ISSUE THREAD

**Issue by creichel** [jenstornell/splitview#100]
It seems like that you're setting a non-existing default value for `splitview.route` in `core/tool.php`:
```
c::get('splitview.route', 'splitview')
```
But the standard route is `site/plugins/splitview`, isnt it? If so, there's a second issue...

**2nd. issue:**

Accessing files directly is restricted by this .htaccess rule that's standard for every Kirby project:

```
# block all files in the site folder from being accessed directly
RewriteRule ^site/(.*) index.php [L]
```
And that's happening:
<img width="250" alt="bildschirmfoto 2016-01-24 um 09 49 59" src="https://cloud.githubusercontent.com/assets/980778/12535344/e47a4262-c27f-11e5-99ff-ac7703226407.png">

A possible solution for this is to go back to `@font-face` icons. What do you think?

**Comment by jenstornell** [comment]
Right now it seems like you are the only one having this issue, but I will do my best to solve it. If anyone else reading this and having this issue, add a comment here.

I will work again tomorrow and can look into it then. In the meantime it would help me if you could answer these questions:

1. What is your value in "splitview.route"? Did you set your own in config.php?
1. What is the url to the panel? Do you have a different url than /panel/?
1. What is the url to your site? Subdomain, folder ect.
1. What version of Kirby are you using?
1. If you right-click an image and choose "View in new tab", what is the url to the image?
1. Do you have html minification or caching plugins on?

## splitview.route

Maybe I should change the naming of "splitview.route" if it's not correct but it's the slug you come TO after hitting the keyboard shortcut, not where you came FROM. The other way around.

## Icon font

It was working before with the icon font? The font was in the plugin folder as well so it would have had the same issues if it would been a htaccess problem.

**Comment by jenstornell** [comment]
I updated the routes today. Maybe it will fix the problem?

https://github.com/jenstornell/splitview/commit/f172db53e2719b469981855fa5d8d74daf523ae4
https://github.com/jenstornell/splitview/blob/master/core/routes.php

**Comment by jenstornell** [comment]
Now everything seems to work, even on a Mac. Even on a PHP server environment. Try it out and let me know.

https://forum.getkirby.com/t/splitview-new-plugin-with-splitscreen-preview/2412/41

**Comment by creichel** [comment]
Sorry for late reply. I've tried that also with an other site. It works there so it seems like to be a problem with my server config - not with the .htaccess, nor with any routes that have to be set or that set up. Thank you for your really professional help!
