### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by jenstornell** [jenstornell/splitview#102]
This file to german:

https://github.com/jenstornell/splitview/blob/master/languages/en.php

**Comment by medienbaecker** [comment]
Here are the German translations:

```
<?php
// Flash menu
l::set('refresh', 'Neu laden');
l::set('copy', 'Kopieren');
l::set('sync', 'Synchronisieren');
l::set('autosync', 'Auto-Sync');

// Zoom menu
l::set('zoom-factor', 'Zoom Faktor');
l::set('reset', 'Zurücksetzen');

// Resize menu
l::set('pixels', 'Pixel (px)');
l::set('percentage', 'Prozent (%)');

// Views menu
l::set('current', 'Aktuell');
l::set('switch', 'Wechseln');
l::set('rows', 'Reihen');
l::set('columns', 'Spalten');
l::set('flip', 'umdrehen');
l::set('distraction-free', 'Ablenkungsfreier Modus');

// Exit menu
l::set('exit-to-this-view', 'Diese Ansicht verlassen');
```

I'm not quite sure about "Exit to this view". Does it mean "Leave this view" or rather "Switch to this view"?

**Comment by jenstornell** [comment]
Thank you so much!

In Splitview there are often two views, the panel view and the site view.

- When chosing "Exit to this view" in the panel view menu it will exit Splitview and go to the panel.
- When chosing "Exit to this view" in the site view menu it will exit Splitview and go to the site (frontend).

I will not have time to implement it before monday but write here again if you need to adjust the "Exit to this view" string.

**Comment by medienbaecker** [comment]
Alright. Thanks!
Well, then it needs to say "Zu dieser Ansicht wechseln". That's more like "Switch to this view" since "Zu dieser Ansicht verlassen" sounds horrible in German and "Verlassen um zu dieser Ansicht zu wechseln" is a tad bit too long. Well, it is German :smile: 
I've updated the initial post.

**Comment by jenstornell** [comment]
Choose what you think is the best translation.

In swedish sync could be translated to "Synk" or "Synkronisera" but there is a shorthand version that is called "Synka" that I choose. It's often a choice.

If someone is not happy about some word there will probably be an issue for it. I will add the translation right after lunch.

Thanks!

**Comment by jenstornell** [comment]
It's added. Does it work well for you?

**Comment by medienbaecker** [comment]
Great, it looks good!
After looking at it on the real thing, I'd suggest changing "Aktuell" to "Aktuelle Ansicht". That's "Current view" in German and might be better understandable.

`l::set('current', 'Aktuell');`
