### ISSUE TITLE
TypeError: null is not an object (evaluating 'button_element.addEventListener')

### ISSUE THREAD

**Issue by creichel** [jenstornell/splitview#71]
Hi there,

I'm getting a JavaScript error when I try to use the splitview plugin:

```
TypeError: null is not an object (evaluating 'button_element.addEventListener')
(anonyme Funktion)tool.js:100
forEach
toggletool.js:98
eventstool.js:94
inittool.js:91
inittool.js:425
(anonyme Funktion)splitview:1:6153
```
I already tried to fix this by adding a `if(button_element == null) return;` but it doesn't look as expected. It seems like that the forEach loop tries to add the event listener to objects which aren't exist. But I don't fully understand your code to fix this...

I tried to use the plugin in Safari, Firefox and Chrome. Every single browser throws the same error...

**Comment by jenstornell** [comment]
Thanks for your report. I will look into it tuesday when I work next time.

**Comment by creichel** [comment]
Forget this. I deactivated the minifyhtml plugin and it works now. Thanks!
