### ISSUE TITLE
Add translation support

### ISSUE THREAD

**Issue by jenstornell** [jenstornell/splitview#99]

**Comment by lukasbestle** [comment]
Some input: You can use the `l::set()` and `l::get()` methods and put the strings into one file per language. Depending on the browser language of the user, one file can be loaded.

**Comment by jenstornell** [comment]
https://getkirby.com/docs/languages/variables

**Comment by lukasbestle** [comment]
Yes, but in your case the language vars shouldn't be saved in the `site` directory but inside your plugin to make updating easier.

**Comment by jenstornell** [comment]
https://getkirby.com/docs/toolkit/api/visitor/acceptedlanguagecode

Thanks as always @lukasbestle for all your help.
